services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./static:/usr/share/nginx/html:ro
  api:
    build: ./api
    expose:
      - "8080"
    volumes:
      - ./data:/app/data
    env_file:
      - ./api/.env

  harness:
    build: ./harness
    expose:
      - "9090"

    volumes:
      - ollama-models:/root/.ollama
      - ./harness:/app
  
volumes:
  ollama-models:
#   pgdata:
